version: '2'
services:
  fastapi:
    container_name: fastapi
    build:
      context: ./
      dockerfile: fastapi.dockerfile
    volumes:
      - './fastapi:/app'
    ports:
      - 8000:8000
    environment:
      MONGODB_HOST: ${MONGO_HOST}
      MONGODB_PORT: ${MONGO_PORT}
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      PYTHONPATH: /app
networks:
  default:
    external: true
    name: lens-mongo_default
