# build or run development image

version: "3.8"
services:
  fastapi:
    build:
      context: ./src
      target: dev
      dockerfile: fastapi.dockerfile
    volumes:
      - "./src:/app"
    ports:
      - 8000:8000