# @format

version: "3.8"
services:
  fastapi:
    container_name: fastapi
    build:
      context: ./src
      dockerfile: fastapi.dockerfile
    volumes:
      - "./src:/app"
    ports:
      - 8000:8000
    environment:
      MONGODB_HOST: ${MONGO_HOST}
      MONGODB_PORT: ${MONGO_PORT}
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      PYTHONPATH: /src
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug --reload

networks:
  default:
    external: true
    name: lens-mongo_default
