# @format

version: "3.8"
services:
  fastapi:
    container_name: fastapi
    restart: on-failure
    build:
      context: ./src
      target: dev
      dockerfile: fastapi.dockerfile
    env_file: 
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug --reload
networks:
  default:
    external: true
    name: lens-mongo_default
