# This is a basic workflow to help you get started with Actions

name: CI with DigitalOcean Container Registry

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the experimental branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #Push to Digital Ocean private Registry
  build-and-push-to-digital-ocean:
    # Ensure test job passes before pushing image.
#     needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        
      - name: build image
        run: make build # use the docker build command from makefile
        
#       - name: Update SHA
#         run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta
      
      - name: set DO registry
        run: export IMAGE_REGISTRY=registry.digitalocean.com/lens
        
      - name: set image name
        run: export IMAGE_NAME=fastapi
        
      - name: tag image
        run: docker tag $IMAGE_REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)
    
      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: login to doctl
        run: doctl registry login --expiry-seconds 600
        
      - name: push image to DO registry
        run: docker push $IMAGE_REGISTRY/$IMAGE_NAME
