# @format

name: CI with DigitalOcean Container Registry

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the experimental branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-push-to-digital-ocean:
    # Ensure test job passes before pushing image.
    # needs: test
    runs-on: ubuntu-latest
    environment: prod-digital-ocean
    env:
      IMAGE_REGISTRY: registry.digitalocean.com/lens
      APPNAME: fastapi
      REPO: lens-backend
    steps:
      - name: checkout master
        uses: actions/checkout@v2

      - name: create .env for `make build` command
        run: |
          touch .env
          echo MONGODB_USER=root >> .env
          echo MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} >> .env
          echo MONGODB_HOST=mongo >> .env
          echo MONGODB_PORT=27017 >> .env
          cat .env

      - name: build image
        run: make build # use the docker build command from makefile

      - name: tag image
        run: docker tag ${REPO}_${APPNAME}:latest ${IMAGE_REGISTRY}/${APPNAME}:$(echo $GITHUB_SHA | head -c7)

      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: login to doctl
        run: doctl registry login --expiry-seconds 600

      - name: push image to DO registry
        run: docker push ${IMAGE_REGISTRY}/${APPNAME}
